### ISSUE TITLE
Enable the Travis hook

### ISSUE THREAD

**Issue by vincent-zurczak** [occiware/occiware.github.io#4]
Someone with administration priveleges should connect on [Travis CI](http://travis-ci.org/) and enable continuous integration for this repository. Currently, the `travis.yml` file uses a Ruby gem to validate all the internal links (pages, images) and HTML correctness.

Only the hook is missing.
Once done, every pull request and/or commit to this repository will result in these verifications.

**Comment by jeanparpaillon** [comment]
Travis CI enabled.
